### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jianwang91** [zwyang6/MoRe#1]
Congratulations on your wonderful work!

But I wonder if you uploaded the wrong version. After running 18000 iters， I only got a mIoU of 36.6.

![image](https://github.com/user-attachments/assets/4c703880-70a2-4cd9-8944-46af935e0c1d)

**Comment by zwyang6** [comment]
Thanks for your attention!
The code was reproduced multiple times before uploading. While performance may fluctuate slightly, results shouldn’t degrade this much. Please ensure all settings follow our instructions.

I am checking the code again and will reply you as soon as possible when the  training process is fininshed ^_^

**Comment by zwyang6** [comment]
> Congratulations on your wonderful work!
> 
> But I wonder if you uploaded the wrong version. After running 18000 iters， I only got a mIoU of 36.6.
> 
> ![image](https://private-user-images.githubusercontent.com/24288056/397617563-4c703880-70a2-4cd9-8944-46af935e0c1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTIxNTMsIm5iZiI6MTczNTAxMTg1MywicGF0aCI6Ii8yNDI4ODA1Ni8zOTc2MTc1NjMtNGM3MDM4ODAtNzBhMi00Y2Q5LTg5NDQtNDZhZjkzNWUwYzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAzNDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZTk5NjcyZTYyNzY5ZmNlNDc0ZDNjMmNhOGI3MDM4OTIwMzMwYmUyYWQ4YjRmNTE3ZmE5ZjU3NWU3OWYxYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j2imDQ2Z3dfvd9FQOi5Mbkz9_IdS8cJeH05gow16aRA)


Hi, thanks for your attention. We have noticed the issue and solved it. The correct version of our code is available now. 
Here is the log that i reproduced recently. Please take a check. [train.log](https://drive.google.com/file/d/1wxYxKKRa2rwyXn_Vw5Ym30HJGNcs7rWl/view?usp=drive_link)
