### ISSUE TITLE
file issue

### ISSUE THREAD

**Issue by lk0429** [zwyang6/MoRe#2]
Thank you very much for your excellent work! 
But I can't find the  "scripts/train_voc.py". 
Can you help me? Thanks!

**Comment by zwyang6** [comment]
Thanks for your attention! We are sorting the related code. It will be available in these two days !

Please give it a STAR to receive the update.

**Comment by zwyang6** [comment]
> Thank you very much for your excellent work! But I can't find the "scripts/train_voc.py". Can you help me? Thanks!

Hi, the code is available now.
